name:  "Sample React CI Pipline / Workflow"

on:
    push:
        branches:
            -main
            -master
            
job:
    build-and-test:
        run-on: ubuntu-latest
        
        
        steps:
            -name: "Setup Node JS"
             user: action/setuo-node@v4
             with:
                node-version: '21'
